pipeline:
  name: demoSecret
  identifier: demoSecret
  projectIdentifier: demoapp
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: check secret
        identifier: check_secret
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: SecretMasking
                  identifier: SecretMasking
                  spec:
                    shell: Sh
                    command: |-
                      echo "Masking the log variable"
                      echo "String value masking"
                      echo "<+stage.variables.demosecret>"
                      echo "Text value masking"
                      echo "<+stage.variables.Delux>"
        variables:
          - name: demosecret
            type: Secret
            description: ""
            value: demo1
          - name: text
            type: Secret
            description: ""
            value: textsecret
          - name: Delux
            type: Secret
            description: ""
            value: FNTS
